### Read users
GET http://localhost:3003/users
Authorization: Bearer {{signin.response.body.$.token}}


### remove unit
DELETE http://localhost:3003/units/2
Authorization: Bearer {{signin.response.body.$.token}}


### Read host in unit
GET http://localhost:3003/hosts/unit/1
Authorization: Bearer {{signin.response.body.$.token}}


### Signup
POST http://localhost:3003/signup
Content-Type: application/json

{
  "login": "eu",
  "password": "123",
  "confirm_password": "123"
}


### Signin
# @name signin
POST http://localhost:3003/signin
Content-Type: application/json

{
  "login": "eu",
  "password": "123"
}


### Signout
# @name signout
GET  http://localhost:3003/signout
